language: minimal

git:
 depth: false
 autocrlf: input

dist: focal

install: true

env:
 global:
  - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
  - GRAVIS="$HOME/gravis"
 matrix:
  - JDK=adopt@1.11
  - JDK=adopt@1.8
  - JDK=adopt@1.14
  - JDK=adopt-openj9@1.11
  - JDK=adopt-openj9@1.8
  - JDK=adopt-openj9@1.14
jobs:
 exclude:
  - arch: arm64
    env: JDK=adopt-openj9@1.8
  - arch: arm64
    env: JDK=adopt-openj9@1.14
before_install:
 - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
 - source $GRAVIS/install-jdk
script:
 - travis_retry sh gradlew check

os:
 - linux
 - osx
 - windows

arch:
 - amd64
 - arm64