_reference_os: &reference_os
 linux
_reference_arch: &reference_arch
                amd64
_reference_jdk: &reference_jdk
                 JDK=adopt@1.11

language: minimal

git:
 depth: false
 autocrlf: input

dist: focal

install: true

env:
 global:
  - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
  - GRAVIS="$HOME/gravis"
  - TERM="dumb"
 matrix:
  - *reference_jdk
  - JDK=adopt@1.8
  - JDK=adopt@1.14
  - JDK=adopt-openj9@1.11
  - JDK=adopt-openj9@1.8
  - JDK=adopt-openj9@1.14

stages:
 - compile
 - style check
 - check
 - test
_workspace_name: &workspace_name
 compiled_env
_reference_machine: &reference_machine
 arch: *reference_arch
 os: *reference_os
 env: *reference_jdk
jobs:
 exclude:
  - arch: arm64
    env: JDK=adopt-openj9@1.8
  - arch: arm64
    env: JDK=adopt-openj9@1.14
  - <<: *reference_machine
    stage: test
 include:
  - <<: *reference_machine
    stage: check
    workspaces:
     use: *workspace_name
    script:
     - travis_retry sh gradlew check
  - <<: *reference_machine
    stage: compile
    workspaces:
     create: *workspace_name
     paths:
      - "$TRAVIS_BUILD_DIR"
      - "$HOME/.gradle"
    script:
      - travis_retry sh gradlew compileKotlin --parallel
  - <<: *reference_machine
    stage: style check
    workspaces:
     use: *workspace_name
    script:
      - travis_retry sh gradlew detekt ktlintCheck --parallel

before_install:
 - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
 - source $GRAVIS/install-jdk
script:
 - travis_retry sh gradlew test

os:
 - *reference_os
 - osx
 - windows

arch:
 - *reference_arch
 - arm64