language: minimal

git:
 depth: false
 autocrlf: input


install: true

env:
 global:
  - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
  - GRAVIS="$HOME/gravis"
  - JDK=adopt@1.11
before_install:
 - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
 - source $GRAVIS/install-jdk
script:
 - travis_retry sh gradlew check

os:
 - linux
 - osx
 - windows

arch:
 - amd64
 - arm64